export type CssProps = {
  display?: string
  alignItems?: string
  justifyContent?: string
  flex?: string
  flexShrink?: string
  gap?: string
  width?: string
  height?: string
  maxHeight?: string
  bgColor?: string
  margin?: string
  marginTop?: string
  marginBottom?: string
  marginLeft?: string
  marginRight?: string
  padding?: string
  paddingTop?: string
  paddingBottom?: string
  paddingLeft?: string
  paddingRight?: string
  position?: string
  top?: string
  bottom?: string
  left?: string
  right?: string
  overflow?: string
  overflowX?: string
  overflowY?: string
  borderRadius?: number
  border?: string
  borderLeft?: string
  borderRight?: string
  url?: string
  color?: string
  fontSize?: string
  fontWeight?: string
  textAlign?: string
  alignSelf?: string
  background?: string
  backdropFilter?: string
  boxShadow?: string
  fontFamily?: string
  fontStyle?: string
  lineHeight?: string
  transform?: string
  cursor?: string
  zIndex?: string
}